name: Python Server Build

on:
  push:
    branches:
      - main
    paths:
      - server/python/**
  pull_request:
    branches:
      - main
    paths:
      - server/python/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/pradyumnakrishna/enigma-protocol/python-server
  IMAGE_TAG: ghcr.io/pradyumnakrishna/enigma-protocol/python-server:${{ github.sha }}

jobs:
  test-and-build:
    defaults:
      run:
        working-directory: server/python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Linters
        run: pip install pylint black
      - name: Lint
        run: |
          pylint *.py
          black --check .

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Set DATE
        run: echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Image Tag to latest
        if: ${{ github.event_name == 'push' }}
        run: echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
      - name: Build and Push Server Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: server/python
          push: true
          tags: ${{ env.IMAGE_TAG }}
